export const DOM_IDS = {
  LESSON_LIST: 'lesson-list',
  THEORY_AREA: 'theory-area',
  EXERCISE_AREA: 'exercise-area',
  EXERCISE_TITLE: 'exercise-title',
  EXERCISE_DESC: 'exercise-desc',
  EDITOR: 'editor',
  EDITOR_LOADING: 'editor-loading',
  RUN_BTN: 'run-btn',
  RESET_BTN: 'reset-btn',
  RESULT_AREA: 'result-area',
  RESULT_MSG: 'result-msg',
  RESULT_OUTPUT: 'result-output',
  SOLUTION_BTN: 'solution-btn',
  RESET_PROGRESS_BTN: 'reset-progress-btn',
  SEARCH_INPUT: 'search-input',
  THEME_TOGGLE: 'theme-toggle',
  MENU_TOGGLE: 'menu-toggle',
  SIDEBAR: 'sidebar',
  SIDEBAR_OVERLAY: 'sidebar-overlay',
  NEXT_LESSON_BTN: 'next-lesson-btn',
} as const;

export const CSS_CLASSES = {
  LESSON_LIST_ITEM: '.lesson-list li',
  MODULE_HEADER: 'sidebar__header',
  COMPLETED: 'completed',
  ACTIVE: 'active',
  HIDDEN: 'hidden',
  SUCCESS: 'success',
  ERROR: 'error',
  INFO: 'info',
  OPEN: 'open',
  CONTENT: '.content',
} as const;
